"""
Pydantic Models for MCP Tool Return Types

This module re-exports Pydantic models for all Cortex MCP tool return types from
domain-specific submodules, enabling FastMCP 2.0 structured output with better
schema generation, automatic validation, and improved IDE support.

All models follow Pydantic v2 best practices. See submodules for definitions:
- file_operations_models: manage_file, rollback_file_version, manager init
- structure_models: check_structure_health, get_structure_info
- rules_models: rules index, get_relevant
- quality_precommit_models: execute_pre_commit_checks, fix_quality, preflight, etc.
- synapse_models: get_synapse_prompts, sync_synapse, fix_roadmap_corruption, etc.
- feedback_models: provide_feedback
- markdown_models: fix_markdown_lint
- health_connection_models: check_mcp_connection_health
- links_models: parse_file_links
- context_analysis_models: context usage, insights, cleanup report, etc.
- roadmap_operations_models: add/remove roadmap entry, append progress/activeContext
"""

from __future__ import annotations

# Re-export ManagersDict for convenience
from cortex.managers.types import ManagersDict
from cortex.validation.models import (
    AllFilesTimestampResult,
    InfrastructureValidationResultModel,
    SingleFileTimestampResult,
)

from .context_analysis_models import (
    CleanupReport,
    ContextAnalysisStatus,
    ContextInsights,
    ContextStatisticsResult,
    ContextUsageEntry,
    ContextUsageStatistics,
    CurrentSessionAnalysisResult,
    FileEffectiveness,
    LearnedPatternsResult,
    RulesExecutionResult,
    SessionLogsAnalysisResult,
    SessionStats,
    TaskTypeInsight,
)
from .feedback_models import (
    LearningSummary,
    ProvideFeedbackErrorResult,
    ProvideFeedbackResult,
    ProvideFeedbackResultUnion,
)
from .file_operations_models import (
    FileMetadata,
    FileMetadataSection,
    FileMetrics,
    FileVersionEntry,
    ManageFileErrorResult,
    ManageFileMetadataResult,
    ManageFileReadResult,
    ManageFileResult,
    ManageFileWriteResult,
    ManagersInitResult,
    RollbackFileVersionErrorResult,
    RollbackFileVersionResult,
    RollbackFileVersionResultUnion,
)
from .health_connection_models import (
    ConnectionHealthErrorResult,
    ConnectionHealthResult,
    ConnectionHealthResultUnion,
    MCPHealthCheckResponse,
)
from .links_models import (
    LinkLocation,
    LinkSummary,
    ParsedMarkdownLink,
    ParsedTransclusion,
    ParseFileLinksErrorResult,
    ParseFileLinksResult,
    ParseFileLinksResultUnion,
)
from .markdown_models import (
    FileResult,
    FixMarkdownLintErrorResult,
    FixMarkdownLintResult,
    FixMarkdownLintResultUnion,
)
from .quality_precommit_models import (
    CheckResult,
    CheckStats,
    CleanupMetadataIndexErrorResult,
    CleanupMetadataIndexResult,
    CleanupMetadataIndexResultUnion,
    DocsAndMemoryBankSyncErrorResult,
    DocsAndMemoryBankSyncResult,
    DocsAndMemoryBankSyncResultUnion,
    ExecutePreCommitChecksErrorResult,
    ExecutePreCommitChecksResult,
    ExecutePreCommitChecksResultUnion,
    FixQualityIssuesErrorResult,
    FixQualityIssuesResult,
    FixQualityIssuesResultUnion,
    PreCommitCheckResult,
    PreCommitResultModel,
    PreflightCheckSummary,
    ProjectConfigStatusModel,
    RunPreflightChecksErrorResult,
    RunPreflightChecksResult,
    RunPreflightChecksResultUnion,
)
from .roadmap_operations_models import (
    AddRoadmapEntryResult,
    AppendActiveContextEntryResult,
    AppendProgressEntryResult,
    RemoveRoadmapEntryResult,
    RemoveRoadmapSectionResult,
)
from .rules_models import (
    RuleInfo,
    RuleMetadata,
    RulesContext,
    RulesDisabledResult,
    RulesErrorResult,
    RulesGetRelevantResult,
    RulesIndexOperationResult,
    RulesIndexResult,
    RulesManagerStatus,
    RulesResultUnion,
)
from .session_models import (
    CheckTaskAvailableResult,
    ClaimTaskErrorResult,
    ClaimTaskResult,
    ConcurrentSession,
    GitStatusSummary,
    InProgressTask,
    ListActiveTasksResult,
    ReleaseTaskResult,
    SessionBrief,
    SessionHandoff,
    SessionHealthSummary,
    SessionRegistryResult,
    SessionStartErrorResult,
    SessionStartResult,
    SessionStartResultUnion,
    TaskLock,
)
from .structure_models import (
    CheckStructureHealthErrorResult,
    CheckStructureHealthResult,
    CheckStructureHealthResultUnion,
    CleanupActionResult,
    CleanupInfo,
    GetStructureInfoErrorResult,
    GetStructureInfoResult,
    GetStructureInfoResultUnion,
    HealthChecks,
    HealthInfo,
    HealthSummary,
    PostCleanupHealth,
    StructureConfig,
    StructureExists,
    StructureInfo,
    StructurePaths,
    StructureSymlinks,
    SymlinkInfo,
)
from .synapse_models import (
    ContextInfo,
    CorruptionMatch,
    FixRoadmapCorruptionErrorResult,
    FixRoadmapCorruptionResult,
    FixRoadmapCorruptionResultUnion,
    GetSynapsePromptsErrorResult,
    GetSynapsePromptsResult,
    GetSynapsePromptsResultUnion,
    GetSynapseRulesErrorResult,
    GetSynapseRulesResult,
    GetSynapseRulesResultUnion,
    PromptInfo,
    RuleInfoModel,
    RulesLoaded,
    SynapseChanges,
    SyncSynapseErrorResult,
    SyncSynapseResult,
    SyncSynapseResultUnion,
    UpdateSynapsePromptErrorResult,
    UpdateSynapsePromptResult,
    UpdateSynapsePromptResultUnion,
    UpdateSynapseRuleErrorResult,
    UpdateSynapseRuleResult,
    UpdateSynapseRuleResultUnion,
)
from .validation_result_models import (
    ValidateDuplicationsResult,
    ValidateErrorResult,
    ValidateInfrastructureResult,
    ValidateQualityAllResult,
    ValidateQualitySingleResult,
    ValidateRoadmapSyncResult,
    ValidateSchemaAllResult,
    ValidateSchemaSingleResult,
    ValidateTimestampsResult,
)

# Union type for validate return (includes validation module models)
ValidateResult = (
    ValidateSchemaSingleResult
    | ValidateSchemaAllResult
    | ValidateDuplicationsResult
    | ValidateQualitySingleResult
    | ValidateQualityAllResult
    | ValidateInfrastructureResult
    | ValidateTimestampsResult
    | ValidateRoadmapSyncResult
    | ValidateErrorResult
    | SingleFileTimestampResult
    | AllFilesTimestampResult
    | InfrastructureValidationResultModel
)

# Re-exports: reference so type checker treats imports as used (reportUnusedImport)
_REEXPORTS = (
    CleanupReport,
    ContextInsights,
    ContextStatisticsResult,
    ContextUsageEntry,
    ContextUsageStatistics,
    CurrentSessionAnalysisResult,
    FileEffectiveness,
    LearnedPatternsResult,
    RulesExecutionResult,
    SessionLogsAnalysisResult,
    SessionStats,
    TaskTypeInsight,
    LearningSummary,
    ProvideFeedbackErrorResult,
    ProvideFeedbackResult,
    ProvideFeedbackResultUnion,
    FileMetadata,
    FileMetadataSection,
    FileMetrics,
    FileVersionEntry,
    ManageFileErrorResult,
    ManageFileMetadataResult,
    ManageFileReadResult,
    ManageFileResult,
    ManageFileWriteResult,
    ManagersInitResult,
    RollbackFileVersionErrorResult,
    RollbackFileVersionResult,
    RollbackFileVersionResultUnion,
    ConnectionHealthErrorResult,
    ConnectionHealthResult,
    ConnectionHealthResultUnion,
    MCPHealthCheckResponse,
    LinkLocation,
    LinkSummary,
    ParseFileLinksErrorResult,
    ParseFileLinksResult,
    ParseFileLinksResultUnion,
    ParsedMarkdownLink,
    ParsedTransclusion,
    FileResult,
    FixMarkdownLintErrorResult,
    FixMarkdownLintResult,
    FixMarkdownLintResultUnion,
    CheckResult,
    CheckStats,
    CleanupMetadataIndexErrorResult,
    CleanupMetadataIndexResult,
    CleanupMetadataIndexResultUnion,
    DocsAndMemoryBankSyncErrorResult,
    DocsAndMemoryBankSyncResult,
    DocsAndMemoryBankSyncResultUnion,
    ExecutePreCommitChecksErrorResult,
    ExecutePreCommitChecksResult,
    ExecutePreCommitChecksResultUnion,
    FixQualityIssuesErrorResult,
    FixQualityIssuesResult,
    FixQualityIssuesResultUnion,
    PreCommitCheckResult,
    PreCommitResultModel,
    PreflightCheckSummary,
    ProjectConfigStatusModel,
    RunPreflightChecksErrorResult,
    RunPreflightChecksResult,
    RunPreflightChecksResultUnion,
    AddRoadmapEntryResult,
    AppendActiveContextEntryResult,
    AppendProgressEntryResult,
    RemoveRoadmapEntryResult,
    RemoveRoadmapSectionResult,
    RuleInfo,
    RuleMetadata,
    RulesContext,
    RulesDisabledResult,
    RulesErrorResult,
    RulesGetRelevantResult,
    RulesIndexOperationResult,
    RulesIndexResult,
    RulesManagerStatus,
    RulesResultUnion,
    CheckStructureHealthErrorResult,
    CheckStructureHealthResult,
    CheckStructureHealthResultUnion,
    CleanupActionResult,
    CleanupInfo,
    GetStructureInfoErrorResult,
    GetStructureInfoResult,
    GetStructureInfoResultUnion,
    HealthChecks,
    HealthInfo,
    HealthSummary,
    PostCleanupHealth,
    StructureConfig,
    StructureExists,
    StructureInfo,
    StructurePaths,
    StructureSymlinks,
    SymlinkInfo,
    ContextInfo,
    CorruptionMatch,
    FixRoadmapCorruptionErrorResult,
    FixRoadmapCorruptionResult,
    FixRoadmapCorruptionResultUnion,
    GetSynapsePromptsErrorResult,
    GetSynapsePromptsResult,
    GetSynapsePromptsResultUnion,
    GetSynapseRulesErrorResult,
    GetSynapseRulesResult,
    GetSynapseRulesResultUnion,
    PromptInfo,
    RuleInfoModel,
    RulesLoaded,
    SynapseChanges,
    SyncSynapseErrorResult,
    SyncSynapseResult,
    SyncSynapseResultUnion,
    UpdateSynapsePromptErrorResult,
    UpdateSynapsePromptResult,
    UpdateSynapsePromptResultUnion,
    UpdateSynapseRuleErrorResult,
    UpdateSynapseRuleResult,
    UpdateSynapseRuleResultUnion,
)

__all__ = [
    "ManagersDict",
    "ValidateResult",
    "CheckTaskAvailableResult",
    "ClaimTaskErrorResult",
    "ClaimTaskResult",
    "ConcurrentSession",
    "GitStatusSummary",
    "InProgressTask",
    "ListActiveTasksResult",
    "ReleaseTaskResult",
    "SessionBrief",
    "SessionHandoff",
    "SessionHealthSummary",
    "SessionRegistryResult",
    "SessionStartErrorResult",
    "SessionStartResult",
    "SessionStartResultUnion",
    "TaskLock",
    "CleanupReport",
    "ContextAnalysisStatus",
    "ContextInsights",
    "ContextStatisticsResult",
    "ContextUsageEntry",
    "ContextUsageStatistics",
    "CurrentSessionAnalysisResult",
    "FileEffectiveness",
    "LearnedPatternsResult",
    "RulesExecutionResult",
    "SessionLogsAnalysisResult",
    "SessionStats",
    "TaskTypeInsight",
    "LearningSummary",
    "ProvideFeedbackErrorResult",
    "ProvideFeedbackResult",
    "ProvideFeedbackResultUnion",
    "FileMetadata",
    "FileMetadataSection",
    "FileMetrics",
    "FileVersionEntry",
    "ManageFileErrorResult",
    "ManageFileMetadataResult",
    "ManageFileReadResult",
    "ManageFileResult",
    "ManageFileWriteResult",
    "ManagersInitResult",
    "RollbackFileVersionErrorResult",
    "RollbackFileVersionResult",
    "RollbackFileVersionResultUnion",
    "ConnectionHealthErrorResult",
    "ConnectionHealthResult",
    "ConnectionHealthResultUnion",
    "MCPHealthCheckResponse",
    "LinkLocation",
    "LinkSummary",
    "ParseFileLinksErrorResult",
    "ParseFileLinksResult",
    "ParseFileLinksResultUnion",
    "ParsedMarkdownLink",
    "ParsedTransclusion",
    "FileResult",
    "FixMarkdownLintErrorResult",
    "FixMarkdownLintResult",
    "FixMarkdownLintResultUnion",
    "CheckResult",
    "CheckStats",
    "CleanupMetadataIndexErrorResult",
    "CleanupMetadataIndexResult",
    "CleanupMetadataIndexResultUnion",
    "DocsAndMemoryBankSyncErrorResult",
    "DocsAndMemoryBankSyncResult",
    "DocsAndMemoryBankSyncResultUnion",
    "ExecutePreCommitChecksErrorResult",
    "ExecutePreCommitChecksResult",
    "ExecutePreCommitChecksResultUnion",
    "FixQualityIssuesErrorResult",
    "FixQualityIssuesResult",
    "FixQualityIssuesResultUnion",
    "PreCommitCheckResult",
    "PreCommitResultModel",
    "PreflightCheckSummary",
    "ProjectConfigStatusModel",
    "RunPreflightChecksErrorResult",
    "RunPreflightChecksResult",
    "RunPreflightChecksResultUnion",
    "AddRoadmapEntryResult",
    "AppendActiveContextEntryResult",
    "AppendProgressEntryResult",
    "RemoveRoadmapEntryResult",
    "RemoveRoadmapSectionResult",
    "RuleInfo",
    "RuleMetadata",
    "RulesContext",
    "RulesDisabledResult",
    "RulesErrorResult",
    "RulesGetRelevantResult",
    "RulesIndexOperationResult",
    "RulesIndexResult",
    "RulesManagerStatus",
    "RulesResultUnion",
    "CheckStructureHealthErrorResult",
    "CheckStructureHealthResult",
    "CheckStructureHealthResultUnion",
    "CleanupActionResult",
    "CleanupInfo",
    "GetStructureInfoErrorResult",
    "GetStructureInfoResult",
    "GetStructureInfoResultUnion",
    "HealthChecks",
    "HealthInfo",
    "HealthSummary",
    "PostCleanupHealth",
    "StructureConfig",
    "StructureExists",
    "StructureInfo",
    "StructurePaths",
    "StructureSymlinks",
    "SymlinkInfo",
    "ContextInfo",
    "CorruptionMatch",
    "FixRoadmapCorruptionErrorResult",
    "FixRoadmapCorruptionResult",
    "FixRoadmapCorruptionResultUnion",
    "GetSynapsePromptsErrorResult",
    "GetSynapsePromptsResult",
    "GetSynapsePromptsResultUnion",
    "GetSynapseRulesErrorResult",
    "GetSynapseRulesResult",
    "GetSynapseRulesResultUnion",
    "PromptInfo",
    "RuleInfoModel",
    "RulesLoaded",
    "SynapseChanges",
    "SyncSynapseErrorResult",
    "SyncSynapseResult",
    "SyncSynapseResultUnion",
    "UpdateSynapsePromptErrorResult",
    "UpdateSynapsePromptResult",
    "UpdateSynapsePromptResultUnion",
    "UpdateSynapseRuleErrorResult",
    "UpdateSynapseRuleResult",
    "UpdateSynapseRuleResultUnion",
]
