"""Re-exports for session, structure, synapse, and shared manager types.

Split from ``models_reexports`` for file-size governance.
"""

from cortex.managers.types import ManagersDict

from .session.connection_models import (
    ConnectionHealthErrorResult,
    ConnectionHealthResult,
    ConnectionHealthResultUnion,
    MCPHealthCheckResponse,
)
from .session.models import (
    CheckTaskAvailableResult,
    ClaimTaskErrorResult,
    ClaimTaskResult,
    ConcurrentSession,
    GitStatusSummary,
    InProgressTask,
    ListActiveTasksResult,
    ReleaseTaskResult,
    SessionBrief,
    SessionHandoff,
    SessionHealthSummary,
    SessionRegistryResult,
    SessionStartErrorResult,
    SessionStartResult,
    SessionStartResultUnion,
    TaskLock,
)
from .structure.structure_models import (
    CleanupActionResult,
    CleanupReport,
)
from .synapse.rules_models import (
    RuleInfo,
    RuleMetadata,
    RulesContext,
    RulesDisabledResult,
    RulesErrorResult,
    RulesGetRelevantResult,
    RulesIndexOperationResult,
    RulesIndexResult,
    RulesManagerStatus,
    RulesResultUnion,
)
from .synapse.synapse_models import (
    ContextInfo,
    CorruptionMatch,
    FixRoadmapCorruptionErrorResult,
    FixRoadmapCorruptionResult,
    FixRoadmapCorruptionResultUnion,
    GetSynapsePromptsErrorResult,
    GetSynapsePromptsResult,
    GetSynapsePromptsResultUnion,
    GetSynapseRulesErrorResult,
    GetSynapseRulesResult,
    GetSynapseRulesResultUnion,
    PromptInfo,
    RuleInfoModel,
    RulesLoaded,
    SynapseChanges,
    SyncSynapseErrorResult,
    SyncSynapseResult,
    SyncSynapseResultUnion,
    UpdateSynapsePromptErrorResult,
    UpdateSynapsePromptResult,
    UpdateSynapsePromptResultUnion,
    UpdateSynapseRuleErrorResult,
    UpdateSynapseRuleResult,
    UpdateSynapseRuleResultUnion,
)

__all__ = [
    "CheckTaskAvailableResult",
    "ClaimTaskErrorResult",
    "ClaimTaskResult",
    "CleanupActionResult",
    "CleanupReport",
    "ConcurrentSession",
    "ConnectionHealthErrorResult",
    "ConnectionHealthResult",
    "ConnectionHealthResultUnion",
    "ContextInfo",
    "CorruptionMatch",
    "FixRoadmapCorruptionErrorResult",
    "FixRoadmapCorruptionResult",
    "FixRoadmapCorruptionResultUnion",
    "GetSynapsePromptsErrorResult",
    "GetSynapsePromptsResult",
    "GetSynapsePromptsResultUnion",
    "GetSynapseRulesErrorResult",
    "GetSynapseRulesResult",
    "GetSynapseRulesResultUnion",
    "GitStatusSummary",
    "InProgressTask",
    "ListActiveTasksResult",
    "MCPHealthCheckResponse",
    "ManagersDict",
    "PromptInfo",
    "ReleaseTaskResult",
    "RuleInfo",
    "RuleInfoModel",
    "RuleMetadata",
    "RulesContext",
    "RulesDisabledResult",
    "RulesErrorResult",
    "RulesGetRelevantResult",
    "RulesIndexOperationResult",
    "RulesIndexResult",
    "RulesLoaded",
    "RulesManagerStatus",
    "RulesResultUnion",
    "SessionBrief",
    "SessionHandoff",
    "SessionHealthSummary",
    "SessionRegistryResult",
    "SessionStartErrorResult",
    "SessionStartResult",
    "SessionStartResultUnion",
    "SyncSynapseErrorResult",
    "SyncSynapseResult",
    "SyncSynapseResultUnion",
    "SynapseChanges",
    "TaskLock",
    "UpdateSynapsePromptErrorResult",
    "UpdateSynapsePromptResult",
    "UpdateSynapsePromptResultUnion",
    "UpdateSynapseRuleErrorResult",
    "UpdateSynapseRuleResult",
    "UpdateSynapseRuleResultUnion",
]
